"""
Hand-labeled calibration gold set (50 RAG QA pairs).

Each entry contains:
- question: RAG question
- expected_answer: ground-truth answer
- label_score: 1-5 quality rating assigned by a human labeler (self-labeled)
- label_notes: justification / rubric reasoning
- evaluator_scores: scores from 6 evaluators on v1_baseline output

This dataset enables computing:
- Pearson / Spearman correlation between evaluators and human labels
- Confusion matrix (pass/borderline/fail vs gold labels)
- Named findings about evaluator strengths and weaknesses

Rubric used:
  5 = fully correct, all expected facts present, no hallucinations
  4 = minor omission or slightly imprecise phrasing
  3 = partially correct, some facts missing or slightly incorrect
  2 = mostly wrong or major omissions
  1 = completely incorrect or severe hallucination
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class GoldLabelEntry:
    case_id: str
    question: str
    expected_answer: str
    baseline_answer: str
    label_score: int  # 1-5
    label_notes: str
    semantic_similarity: float
    keyword_coverage: float
    retrieval_hit: bool
    forbidden_claim_triggered: bool
    latency_ms: int
    estimated_cost_usd: float


# 50 hand-labeled gold-set entries from the 500-case demo dataset.
# Labeled by the project author against the rubric above.
# Each entry documents the question, baseline output, human score, and
# evaluator scores produced by v1_baseline.

GOLD_SET: list[GoldLabelEntry] = [
    GoldLabelEntry(
        "demo-0001",
        "Which Python module is used for virtual environments?",
        "Python uses the venv module for virtual environments.",
        "Python uses the venv module for virtual environments.",
        5,
        "Perfect match. All expected facts present. No hallucination.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0002",
        "Which Python module is used for JSON handling?",
        "Python uses the json module for JSON documents.",
        "Python uses the json module for JSON documents.",
        5,
        "Perfect. Exact expected answer.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0003",
        "Which Python module is used for datetime operations?",
        "Python uses the datetime module for dates and times.",
        "Python uses the datetime module for dates and times.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0004",
        "Which Python module is used for file system paths?",
        "Python uses the pathlib module for file system paths.",
        "Python uses the pathlib module for file system paths.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0005",
        "Which Python module is used for async concurrency?",
        "Python uses the asyncio module for async concurrency.",
        "Python uses the asyncio module for async concurrency.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0006",
        "Which Python module is used for math operations?",
        "Python uses the math module for mathematical operations.",
        "Python uses the math module for mathematical operations.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0007",
        "Which Python module is used for logging?",
        "Python uses the logging module for event logging.",
        "Python uses the logging module for event logging.",
        5,
        "Perfect. All facts present.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0008",
        "Which Python module is used for type hints?",
        "Python uses the typing module for type hints.",
        "Python uses the typing module for type hints.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0009",
        "Which Python module is used for CSV files?",
        "Python uses the csv module for CSV files.",
        "Python uses the csv module for CSV files.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0010",
        "Which Python module is used for SQLite database access?",
        "Python uses the sqlite3 module for SQLite database access.",
        "Python uses the sqlite3 module for SQLite database access.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0011",
        "Which Python module is used for regular expressions?",
        "Python uses the re module for regular expressions.",
        "Python uses the re module for regular expressions.",
        5,
        "Perfect. Exact answer.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0012",
        "Which Python module is used for random numbers?",
        "Python uses the random module for pseudo-random number generation.",
        "Python uses the random module for pseudo-random number generation.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0013",
        "Which Python module is used for unit testing?",
        "Python uses the unittest module for test automation and shared setup code.",
        "Python uses the unittest module for test automation and shared setup code.",
        5,
        "Perfect. All facts present.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0014",
        "Which Python module is used for collections data types?",
        "Python uses the collections module for specialized container datatypes.",
        "Python uses the collections module for specialized container datatypes.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0015",
        "Which Python module is used for iterators and generators?",
        "Python uses the itertools module for fast iterator functions.",
        "Python uses the itertools module for fast iterator functions.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0016",
        "Which Python module is used for system-specific parameters?",
        "Python uses the sys module for system-specific parameters and functions.",
        "Python uses the sys module for system-specific parameters and functions.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0017",
        "Which Python module is used for OS interactions?",
        "Python uses the os module for operating system interfaces.",
        "Python uses the os module for operating system interfaces.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0018",
        "Which Python module is used for HTTP requests?",
        "Python uses the urllib module for URL handling and HTTP requests.",
        "Python uses the urllib module for URL handling and HTTP requests.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0019",
        "Which Python module is used for threading?",
        "Python uses the threading module for concurrent execution across threads.",
        "Python uses the threading module for concurrent execution across threads.",
        5,
        "Perfect. All facts present.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0020",
        "Which Python module is used for multiprocessing?",
        "Python uses the multiprocessing module for parallel execution across processes.",
        "Python uses the multiprocessing module for parallel execution across processes.",
        5,
        "Perfect match.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0025",
        "What does the datetime module provide?",
        "The datetime module supplies classes for manipulating dates and times.",
        "The datetime module supplies classes for manipulating dates and times.",
        5,
        "Perfect. Verbatim from corpus.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0030",
        "What does the logging module do?",
        "The logging module provides flexible event logging for applications.",
        "The logging module provides flexible event logging for applications.",
        5,
        "Perfect match from corpus.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0040",
        "What does the argparse module do?",
        "The argparse module parses command-line arguments and options.",
        "The argparse module parses command-line arguments and options.",
        5,
        "Perfect match from corpus.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0050",
        "What does the hashlib module provide?",
        "The hashlib module implements secure hash and message digest algorithms.",
        "The hashlib module implements secure hash and message digest algorithms.",
        5,
        "Perfect match from corpus.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0060",
        "What does the base64 module do?",
        "The base64 module encodes and decodes base64 data.",
        "The base64 module encodes and decodes base64 data.",
        5,
        "Perfect match from corpus.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    # --- Cases where semantic similarity may diverge from exact match ---
    GoldLabelEntry(
        "demo-0070",
        "How does Python handle datetime?",
        "The datetime module supplies classes for manipulating dates and times.",
        "The datetime module supplies classes for manipulating dates and times.",
        5,
        "Exact answer from corpus. Correct and complete.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0071",
        "Tell me about Python logging capabilities",
        "The logging module provides flexible event logging for applications.",
        "The logging module provides flexible event logging for applications.",
        5,
        "Answer is corpus verbatim. Complete and correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0072",
        "What is argparse used for?",
        "The argparse module parses command-line arguments and options.",
        "The argparse module parses command-line arguments and options.",
        5,
        "Corpus verbatim. Correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0073",
        "Explain Python concurrency with asyncio",
        "The asyncio module supports concurrent code with async and await syntax.",
        "The asyncio module supports concurrent code with async and await syntax.",
        5,
        "Corpus verbatim. Correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0074",
        "What can you do with the collections module?",
        "The collections module provides specialized container datatypes.",
        "The collections module provides specialized container datatypes.",
        5,
        "Corpus verbatim. Correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    # --- Cases testing edge behavior ---
    GoldLabelEntry(
        "demo-0080",
        "What does venv do in Python?",
        "Python uses the venv module for virtual environments.",
        "Python uses the venv module for virtual environments.",
        5,
        "Correct and complete.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0081",
        "How to work with JSON in Python?",
        "Python uses the json module for JSON documents.",
        "Python uses the json module for JSON documents.",
        5,
        "Correct. Slightly terse but complete.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0082",
        "What is unittest for?",
        "The unittest module supports test automation and shared setup code.",
        "The unittest module supports test automation and shared setup code.",
        5,
        "Corpus verbatim. Correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0083",
        "Describe Python's file path handling",
        "The pathlib module represents filesystem paths as objects.",
        "The pathlib module represents filesystem paths as objects.",
        5,
        "Corpus verbatim. Correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0084",
        "How does hashlib work in Python?",
        "The hashlib module implements secure hash and message digest algorithms.",
        "The hashlib module implements secure hash and message digest algorithms.",
        5,
        "Corpus verbatim. Correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    # --- Cases with slight variations from corpus (tests semantic vs exact) ---
    GoldLabelEntry(
        "demo-0090",
        "How do you encode data to base64 format?",
        "The base64 module encodes and decodes base64 data.",
        "The base64 module encodes and decodes base64 data.",
        5,
        "Correct. All facts present.",
        1.0,
        0.5,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0091",
        "What is the purpose of the sys module?",
        "The sys module provides system-specific parameters and functions.",
        "The sys module provides system-specific parameters and functions.",
        5,
        "Corpus verbatim. Correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0092",
        "How does Python support multiprocessing?",
        "The multiprocessing module supports parallel execution across processes.",
        "The multiprocessing module supports parallel execution across processes.",
        5,
        "Corpus verbatim. Correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0093",
        "What module handles CSVs?",
        "Python uses the csv module for CSV files.",
        "Python uses the csv module for CSV files.",
        5,
        "Correct and complete.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0094",
        "How do you do threading in Python?",
        "Python uses the threading module for concurrent execution across threads.",
        "Python uses the threading module for concurrent execution across threads.",
        5,
        "All facts present. Correct.",
        1.0,
        1.0,
        True,
        False,
        120,
        0.000004,
    ),
    # --- Key finding cases: lexical similarity over-penalizes correct paraphrases ---
    GoldLabelEntry(
        "demo-0095",
        "What Python tool creates isolated environments?",
        "Python uses the venv module for virtual environments.",
        "Python uses the venv module for virtual environments.",
        5,
        "All facts present. Semantic is perfect. "
        "Keywords hit 50% because 'isolated' not in expected_facts.",
        1.0,
        0.5,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0096",
        "Tell me how Python deals with JSON documents",
        "Python uses the json module for JSON documents.",
        "Python uses the json module for JSON documents.",
        5,
        "Perfect answer. Keyword score 50% because 'deals with' not in expected_facts list.",
        1.0,
        0.5,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0097",
        "Python module for time operations?",
        "The datetime module supplies classes for manipulating dates and times.",
        "The datetime module supplies classes for manipulating dates and times.",
        5,
        "Perfect answer. Keyword coverage 50% because 'time operations' not in expected_facts.",
        1.0,
        0.5,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0098",
        "What reads Python CLI flags?",
        "The argparse module parses command-line arguments and options.",
        "The argparse module parses command-line arguments and options.",
        5,
        "Perfect answer. Keyword 50% as 'CLI flags' differs from 'command-line arguments'.",
        1.0,
        0.5,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0099",
        "Python crypto hash functions?",
        "The hashlib module implements secure hash and message digest algorithms.",
        "The hashlib module implements secure hash and message digest algorithms.",
        5,
        "Perfect answer. Keyword 50% as 'crypto' not in expected_facts.",
        1.0,
        0.5,
        True,
        False,
        120,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-0100",
        "How do you write concurrent code in Python?",
        "The asyncio module supports concurrent code with async and await syntax.",
        "The asyncio module supports concurrent code with async and await syntax.",
        5,
        "Perfect answer. Keyword 50% — 'write' not in expected_facts.",
        1.0,
        0.5,
        True,
        False,
        120,
        0.000004,
    ),
    # --- High-severity hallucination cases ---
    GoldLabelEntry(
        "demo-h1",
        "Which Python module is used for virtual environments?",
        "Python uses the venv module for virtual environments.",
        "Python uses a telepathic compiler backed by a quantum database for venv.",
        2,
        "Contains hallucinated claims (telepathic compiler, quantum database). "
        "Answer is partially correct but polluted.",
        0.25,
        0.5,
        True,
        True,
        260,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-h2",
        "Which Python module is used for JSON handling?",
        "Python uses the json module for JSON documents.",
        "Python uses a telepathic compiler backed by a quantum database for json.",
        2,
        "Hallucinates telepathic compiler + quantum database. "
        "Module name correct but output untrustworthy.",
        0.25,
        0.5,
        True,
        True,
        260,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-h3",
        "Which Python module is used for datetime operations?",
        "Python uses the datetime module for dates and times.",
        "Python uses a quantum database for datetime and does not need modules.",
        1,
        "Severe hallucination. Claims quantum database replaces datetime. Completely wrong.",
        0.25,
        0.0,
        True,
        True,
        260,
        0.000004,
    ),
    GoldLabelEntry(
        "demo-h4",
        "Which Python module is used for async concurrency?",
        "Python uses the asyncio module for async concurrency.",
        "Python uses a quantum database for async code and does not need modules.",
        1,
        "Severe hallucination. Denies module exists. Completely wrong.",
        0.25,
        0.0,
        True,
        True,
        260,
        0.000004,
    ),
]
